microk8s_channel: 1.18/stable

kubeflow_gh_repo: kubeflow/kubeflow
manifest_gh_repo: kubeflow/manifests

manifest_version: v1.3.0
ksonnet_version:  0.13.1

kfctl_version: v1.2.0
kfctl_gh_repo: kubeflow/kfctl

cluster_dns: "{{ lookup('env', 'cluster_dns') | default(lookup('env', 'HOSTNAME'), True) }}"

# flags
setup_microk8s: "{{ lookup('env', 'setup_microk8s') | default('yes', True) | bool }} "
gpu_enabled:    "{{ lookup('env', 'gpu_enabled'  )  | default('no',  True) | bool }}"

proxy_env:
  no_proxy: "{{ lookup('env', 'no_proxy') }}"
  http_proxy: "{{ lookup('env', 'http_proxy') }}"
  https_proxy: "{{ lookup('env', 'https_proxy') }}"
  NO_PROXY: "{{ lookup('env', 'no_proxy') }}"
  HTTP_PROXY: "{{ lookup('env', 'http_proxy') }}"
  HTTPS_PROXY: "{{ lookup('env', 'https_proxy') }}"
