deployment_name:  default
microk8s_channel: 1.18/stable
kubeflow_gh_repo: kubeflow/kubeflow
manifest_version: v1.0.2
ksonnet_version:  0.13.1
kfctl_version: v1.0.2
kfctl_gh_repo: kubeflow/kfctl

cluster_dns: com.github.jw3

proxy_env:
  http_proxy: "{{ lookup('env', 'playbook_http_proxy') | default('') }}"
  https_proxy: "{{ lookup('env', 'playbook_https_proxy') | default('') }}"
  HTTP_PROXY: "{{ lookup('env', 'playbook_http_proxy') | default('') }}"
  HTTPS_PROXY: "{{ lookup('env', 'playbook_https_proxy') | default('') }}"
  no_proxy: "{{ lookup('env', 'playbook_no_proxy') | default('') }}"
