deployment_name:  default
microk8s_channel: 1.17/stable
kubeflow_version: v1.0
manifest_version: v1.0.0
kubeflow_gh_repo: kubeflow/kubeflow
ksonnet_version:  0.13.1
kfctl_version: 1.0-0-g94c35cf


cluster_dns: com.github.jw3

proxy_env:
  http_proxy: "{{ lookup('env', 'playbook_http_proxy') | default('') }}"
  https_proxy: "{{ lookup('env', 'playbook_https_proxy') | default('') }}"
  HTTP_PROXY: "{{ lookup('env', 'playbook_http_proxy') | default('') }}"
  HTTPS_PROXY: "{{ lookup('env', 'playbook_https_proxy') | default('') }}"
  no_proxy: "{{ lookup('env', 'playbook_no_proxy') | default('') }}"
