---
- name: Set up Microk8s
  hosts: localhost
  gather_facts: no
  become: yes
  pre_tasks:
    - name: set snap proxy
      shell: |
        snap set system proxy.http="{{ proxy_env.https_proxy }}"
        snap set system proxy.https="{{ proxy_env.https_proxy }}"

    - name: create temp workspace
      tempfile:
        state: directory
        suffix: microkf
      register: workspace
      become: no

  roles:
    - microk8s

- name: Set up Kubeflow
  hosts: localhost
  roles:
    - kubeflow
