---
- name: install microk8s
  snap:
    name: microk8s
    classic: yes
    channel: "{{ microk8s_channel }}"

- name: alias kubectl
  shell: |
    snap alias microk8s.kubectl k
    snap alias microk8s.kubectl kubectl

- name: alias kubectl
  shell: |
    snap alias microk8s.kubectl k
    snap alias microk8s.kubectl kubectl

- name: enable alpha api
  lineinfile:
    path: /var/snap/microk8s/current/args/kube-apiserver
    line: '--runtime-config=settings.k8s.io/v1alpha1=true'

- name: enable pod presets
  lineinfile:
    path: /var/snap/microk8s/current/args/kube-apiserver
    line: '--enable-admission-plugins="PodPreset"'

- name: restart kube api server
  systemd:
    state: restarted
    daemon_reload: yes
    name: snap.microk8s.daemon-apiserver.service

# if https proxy is required
- name: containerd proxy
  lineinfile:
    path: /var/snap/microk8s/current/args/containerd-env
    regexp: '^HTTPS_PROXY='
    line: 'HTTPS_PROXY={{ proxy_env.https_proxy }}'
  when: proxy_env.https_proxy != ""

- name: restart containerd
  systemd:
    state: restarted
    daemon_reload: yes
    name: snap.microk8s.daemon-containerd.service
  when: proxy_env.https_proxy != ""

- name: enable microk8s features
  shell: microk8s.enable dns dashboard storage gpu ingress

#
# istio is broken in microk8s at 1.17
# pull in istio 1.3.6 here to fix issue
# prefetch itsio so microk8s doesnt have to
#

- name: create istio workspace
  file:
    path: "{{ workspace.path }}/istio"
    state: directory

- name: create snap current bin
  file:
    path: /var/snap/microk8s/current/bin/
    state: directory

- name: create istio snap dir
  file:
    path: /var/snap/microk8s/current/actions/istio/
    state: directory

- name: download istio 1.3.6 (hack)
  unarchive:
    src: "https://github.com/istio/istio/releases/download/1.3.6/istio-1.3.6-linux.tar.gz"
    dest: "{{ workspace.path }}/istio"
    extra_opts:
      - --strip=1
    remote_src: yes
  environment: "{{ proxy_env }}"

- name: install istioctl
  copy:
    src: "{{ workspace.path }}/istio/bin/istioctl"
    dest: /var/snap/microk8s/current/bin/
  become: yes

- name: copy istio crds to snap path
  copy:
    src: "{{ item }}"
    dest: /var/snap/microk8s/current/actions/istio/
  with_fileglob:
    - "{{ workspace.path }}/istio/install/kubernetes/helm/istio-init/files/crd-??.yaml"
  become: yes

- name: copy istio demo yaml to snap path
  copy:
    src: "{{ item }}"
    dest: /var/snap/microk8s/current/actions/istio/
  with_fileglob:
    - "{{ workspace.path }}/istio/install/kubernetes/istio-demo*yaml"
  become: yes

#
# end of istio workaround
#

- name: enable microk8s features (istio)
  shell: echo "n" | microk8s.enable istio
  environment: "{{ proxy_env }}"

- name: export kubectl config file
  shell:
    chdir: $HOME/.kube
    cmd: kubectl config view --raw > config
  become: no
