---

- name: create tmp workspace bin
  file:
    path: "{{ workspace.path }}/bin"
    state: directory

- name: create manifests workspace
  file:
    path: "{{ workspace.path }}/manifests"
    state: directory

- name: configure resources
  template:
    src: "{{ item }}"
    dest: "{{ workspace.path }}/{{ item | basename | regex_replace('\\.j2','') }}"
  with_fileglob:
    - "{{ role_path }}/templates/*.j2"

- name: download kustomize
  get_url:
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_linux_amd64
    dest: "{{ workspace.path }}/bin/kustomize"
    mode: '0755'
  environment: "{{ proxy_env }}"

- name: get kubeflow manifests
  unarchive:
    src: "https://github.com/kubeflow/manifests/archive/refs/tags/{{ manifest_version }}.tar.gz"
    dest: "{{ workspace.path }}/manifests"
    remote_src: yes
    extra_opts: [ --strip-components=1 ]
  environment: "{{ proxy_env }}"

#- name: patch argo container runtime executor
#  lineinfile:
#    path: "{{ workspace.path }}/app/kustomize/argo/base/params.env"
#    regexp: '^containerRuntimeExecutor='
#    line: 'containerRuntimeExecutor=pns'

- name: apply manifests
  shell:
    cmd: "{{ workspace.path }}/bin/kustomize build example | kubectl apply -f -"
    chdir: "{{ workspace.path }}/manifests"
  retries: 5
  delay: 5
  register: apply_manifest_result
  until: apply_manifest_result is succeeded

- name: apply kf ingress
  shell:
    cmd: "kubectl apply -f {{ workspace.path }}"
  retries: 5
  delay: 2
  register: kubectl_ingress_result
  until: kubectl_ingress_result is succeeded

- name: remove spartacus
  shell:
    cmd: "kubectl -n kubeflow delete deploy -l app=spartakus"
